apiVersion: apps/v1
kind: Deployment
metadata:
  name: "acme"
spec:
  selector:
    matchLabels:
      app: "acme"
  replicas:  {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "acme"
    spec:
      containers:
      - image: {{ .Values.image }}
        name: "acme"
        env:
          - name: DB_HOSTNAME
            value: {{ .Values.dbhost }}
          - name: DB_USERNAME
            value: {{ .Values.dbusername }}
          - name: DB_NAME
            value: {{ .Values.dbname }}
          - name: DB_PASSWORD
            value: {{ .Values.dbpassword }}
          - name: "PORT"
            value: "80"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP